name: kz_h
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^8.0.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  flutter_svg: ^2.0.16
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  form_validation: ^3.2.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  skeletonizer: 2.1.0
  loading_animation_widget: ^1.3.0
  bot_toast: ^4.1.3
  internet_connection_checker: ^3.0.1
  device_info_plus: ^11.2.2
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2

dev_dependencies:
  auto_route_generator: 
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.3

flutter:

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animations/
flutter_intl:
  enabled: true
